---
title: "MathDataSet"
author: "Shiyue"
date: "June 16, 2017"
output: html_document
---
option+cammand+i
```{r}
## Set Working Directory
setwd("/Users/shiyuezheng/Desktop/Charles")
```

```{r}
##Read file 
data <- read.csv("MathDataset-V1.csv", header = TRUE)#You need to tell R that the first row is the headings for the variables
#Create q.number variable
data$q.number <- 1
#Order by student and time
data <- dplyr::arrange(data, Anon.Student.Id, time)
#Create new data set that summarizes the number of questions per student
new.data <- data %>% group_by(Anon.Student.Id) %>% summarise(sum(q.number))
```


## Attempt & Error Msg
1.group_by(.,Anon Student Id)  
Error: unexpected symbol in "group_by(.,Anon Student"  
2. q.number<-group_by(.,Anon Student Id)  
Error: unexpected symbol in "q.number<-group_by(.,Anon Student"  
3. q.number<-group_by(MathDataset-V1,Anon Student Id)  
Error: unexpected symbol in "q.number<-group_by(MathDataset-V1,Anon Student"  
```{r}
##Create a variable called q.number

```

